language: bash
services: docker

env:
  - VERSION=0.7.1.4
  - VERSION=latest

before_script:
  - image="mozillazg/beansdb:$VERSION"

script:
  - ./make.sh build $VERSION

after_script:
  - docker images
